name: CI

on:
  #push:
    #branches:
    #  - main
  pull_request:
    branches:
      - uat
  workflow_dispatch:


jobs:

  # Uncomment the following job if SAST scanning is required in the future
   SAST-scan:
     runs-on: ubuntu-107
     continue-on-error: true
     permissions:
       actions: read
       contents: read
       security-events: write
     strategy:
       fail-fast: false
       matrix:
         language: ['javascript']
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Initialize CodeQL
         uses: github/codeql-action/init@v2
         with:
           languages: ${{ matrix.language }}
       - name: Autobuild
         uses: github/codeql-action/autobuild@v2
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v2
         with:
           category: "/language:${{ matrix.language }}"

  # Uncomment this job for GitHub Advanced Security policy checks
   GHASPolicy:
     name: Check Existing Alerts
     runs-on: ubuntu-107
     permissions:
       contents: read
       security-events: read
       pull-requests: write
     steps:
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
      # - name: Advanced Security Policy as Code
       #  uses: actions/policy-as-code@main
        # with:
        #   policy-path: policies/default.yml
        #   policy-branch: uat
